### ISSUE TITLE
Create simple hamburger menu for mobile devices.

### ISSUE THREAD

**Issue by corpulent** [bazoon-nyc/site#15]

**Comment by hellojeehae** [comment]
Navigation 

font size 24px weight regular

![320_navigation](https://github-cloud.s3.amazonaws.com/assets/15158815/10566218/93e11f1a-75ae-11e5-85ee-82f53216bda6.png)

**Comment by corpulent** [comment]
@hellojeehae can i get png of that X on the top left?

**Comment by hellojeehae** [comment]
![icon_nav_x](https://cloud.githubusercontent.com/assets/15158815/10566957/58148610-75c3-11e5-82eb-f912476885eb.png)

**Comment by hellojeehae** [comment]
Can we center align it at all? and fade out the rest of the page with black 85% opacity maybe?

**Comment by corpulent** [comment]
@hellojeehae the way the menu behaves right now is that it is fixed,  and follows the user around.  Are you saying that when I click the burger,  the black thing pops up with the links and the X over the top portion of the page?  Does it follow the user around,  like the standard menu does?  Let me know.  Sorry,  I was just confused on how it all needs to behave.

I also don't understand what you mean by having the whole page fade to black with opacity.

Why dont I just center the link text,  and have the same behavior of the menu like it is for desktop?  Like the way it follows the scrolling.

**Comment by hellojeehae** [comment]
black popup with the X over the top works for me. http://www.codeandtheory.com/things-we-make closest example i could find. hope this helps. no need to fade background if we can do this.
