### ISSUE TITLE
7th module paddings

### ISSUE THREAD

**Issue by hellojeehae** [bazoon-nyc/site#28]
Top and bottom padding should match 6th module, 5th module. Double padding(from currently padding) between rows of logos.

Attached 6th module here to display correct padding 
![screen shot 2015-10-16 at 10 53 47 am](https://cloud.githubusercontent.com/assets/15158815/10544963/3eb9c19c-73f4-11e5-8a78-8a545dc61db3.png)

![screen shot 2015-10-16 at 10 55 47 am](https://cloud.githubusercontent.com/assets/15158815/10544928/1570d654-73f4-11e5-95af-46b63a612fb3.png)

**Comment by corpulent** [comment]
This is was fixed in a previous push.  Double check if what is up is correct,  and close this issue.
