### ISSUE TITLE
5th module padding at mobile breakpoint

### ISSUE THREAD

**Issue by hellojeehae** [bazoon-nyc/site#38]
Padding for top and bottom is 48px
Padding between paragraphs are 20px

![screen shot 2015-10-16 at 4 27 39 pm](https://cloud.githubusercontent.com/assets/15158815/10552531/84160538-7422-11e5-9dac-3bd17f3a8529.png)

**Comment by corpulent** [comment]
Issue referenced by this commit https://github.com/bazoon-nyc/site/commit/7e1251a5a5fc0f9bbfc3ba5a65f2c9f4da79ab7f
