### ISSUE TITLE
Footer links on the bottom

### ISSUE THREAD

**Issue by hellojeehae** [bazoon-nyc/site#41]
Need links to the following. 

<img width="777" alt="screen shot 2015-10-18 at 11 34 46 am" src="https://cloud.githubusercontent.com/assets/15158815/10564725/451e7782-758c-11e5-89ec-28b7cfa7d9e4.png">

**Comment by hellojeehae** [comment]
https://twitter.com/bazoonnyc for twitter
https://www.linkedin.com/company/bazoon for linkedin

**Comment by corpulent** [comment]
@hellojeehae do the links need to be so separate?  Can also make the footer height shorter?

**Comment by hellojeehae** [comment]
That works for me! for mobile breakpoint can the links stack one after another like the navigation. Center aligned as well.
